; TODO INSERT CONFIG CODE HERE USING CONFIG BITS GENERATOR
#include "p16f887.inc"

; CONFIG1
; __config 0xE0D4
 __CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
; CONFIG2
; __config 0xFFFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
 
VARIABLES UDATA	
    ADC_C1  RES 1
    ADC_C0 RES 1
    W_RAM RES 1
    STATUS_RAM RES 1
 
RES_VECT  CODE    0x0000            ; processor reset vector
    GOTO    START                   ; go to beginning of program

 

; TODO ADD INTERRUPTS HERE IF USED
INTER CODE 0x0004
SAVE:
    MOVWF   W_RAM
    SWAPF   STATUS,W
    MOVWF   STATUS_RAM
ISR:
    BCF	PIR1,6 ;BANDERA DEL ADC
    
    BTFSS   ADCON0,2
    GOTO ES_0
    
    MOVF    ADRESH,W
    MOVWF  ADC_C1
    BCF	ADCON0,2
    GOTO LOAD
    
ES_0
    MOVF   ADRESH,W
    MOVWF   ADC_C0
    BSF	ADCON0,2
    
    
LOAD:
    
    NOP
    NOP
    NOP
    NOP
    BSF	ADCON0, 1 ;INICIA CONVERSION
    SWAPF   STATUS_RAM,W
    MOVWF  STATUS
    SWAPF   W_RAM,F
    SWAPF   W_RAM,W
    RETFIE
    
MAIN_PROG CODE                      ; let linker place main program

START
    BSF	STATUS,6
    BSF	STATUS,5 ;BANCO 3
    
    MOVLW   .255
    MOVWF   ANSEL ;SE ACTIVAN LOS PINES ANALOGICOS
    
    BCF	STATUS,6 ;BANCO 1
    
    MOVWF   TRISA ;ENTRADAS
    CLRF    TRISC
    BSF	INTCON,7 ;INTERRUPCIONES ACTIVADAS
    BSF	INTCON,6 ;INTERRUPCIONES PERIFERICAS ACTIVAS
    
    BSF	PIE1,6	;INTERRUPCION DEL ADC ACTIVA
    
    BCF	ADCON1, 7 ;JUSTIFICADO A LA DERECHA
    BCF	ADCON1, 5   ;VSS
    BCF	ADCON1, 4 ;VDD
    
    MOVLW   .187
    MOVWF   PR2
    
    BCF	STATUS,5 ;BANCO 0
    
    MOVLW   B'01000001' ;FOSC/8 ADC ENCENDIDO CANAL 0
    MOVWF   ADCON0
    
    BSF	T2CON,2 ;TIMER 2 ENCENDIDO
    BSF	T2CON,1 ;PRESCALER DE 16
    ;------ CONFIGURACION DE PWM-------------
    MOVLW   B'00001100' 
    MOVWF   CCP1CON
    MOVWF   CCP2CON
    
    BSF	ADCON0,1 ;INICIA LA CONVERSON
    
    
    
    
LOOP:
    
    MOVF    ADC_C0,W
    MOVWF   CCPR1L
    MOVF    ADC_C1,W
    MOVWF   CCPR2L
    GOTO    LOOP
    
    END