; TODO INSERT CONFIG CODE HERE USING CONFIG BITS GENERATOR
; PIC16F887 Configuration Bit Settings

; Assembly source line config statements

#include "p16f887.inc"

; CONFIG1
; __config 0xE0D4
 __CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
; CONFIG2
; __config 0xFFFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF


VARS UDATA 

ADC	RES 1
EEPROM_READ RES 1
ANTIRREBOTE RES 1
W_RAM	RES 1
STATUS_RAM RES 1
DELAY1 RES 1
    
RES_VECT  CODE    0x0000            ; processor reset vector
    GOTO    START                   ; go to beginning of program

INT_VECT CODE 0x0004
; TODO ADD INTERRUPTS HERE IF USED
SAVE:
    MOVWF   W_RAM
    SWAPF   STATUS,W
    MOVWF   STATUS_RAM
ISR: ;COMO SOLO SE USA LA INTERRUPCION DEL ADC NO SE VERIFICARA 
    BCF	STATUS,RP1
    BCF	STATUS,RP0 ;BANCO 0
    
    BCF	PIR1,ADIF 
    MOVF    ADRESH,W
    MOVWF  ADC
    MOVWF   PORTB
    BSF	ADCON0	,GO
LOAD:
    SWAPF   STATUS_RAM, W
    MOVWF   STATUS
    SWAPF   W_RAM,F
    SWAPF   W_RAM,W
    RETFIE

MAIN_PROG CODE                      ; let linker place main program

START
    BSF	STATUS,6
    BSF	STATUS,5 ;BANCO 3 
    
    CLRF	ANSEL
    BSF	ANSEL,0 ; AN0 COMO ENTRADA
    CLRF	ANSELH ;PUERTO B COMO IO DIGITAL
    
    BCF	EECON1,7 ;ACCESANDO A LA MEMORIA EEPROM
    
    BCF	STATUS, 5 ;BANCO 2
    
    CLRF    EEADR ;LA DIRECCION DE LA EEPROM A USAR SIEMPRE SERA LA 0x00
    
   BCF	STATUS,6 
   BSF	STATUS,5 ;BANCO 1
   
   CLRF	TRISB
   CLRF	TRISC
   CLRF	TRISD
   
   MOVLW    .255
   MOVWF    TRISA ;PUERTO A COMO ENTRADA
   
   BSF	INTCON, GIE 
   BSF	INTCON, PEIE
   
   BSF	PIE1, ADIE ;INTERRUPCION DEL ADC HABILITADA
   
   CLRF	ADCON1 ;JUSTIFICADO A LA DERECHA, VDD Y VSS COMO REFERENCIAS
   
   BCF	STATUS, RP0 ; BANCO 0
   
   MOVLW    B'01000001' ;FOSC/8 CANAL CERO Y ADC ENCENDIDO
   MOVWF    ADCON0
   
   CLRF	PORTB
   CLRF	PORTD
   
   CLRF	ADC
   CLRF	EEPROM_READ
   
   BSF	ADCON0,GO
   
LOOP:
    BCF	STATUS,RP1
    BCF	STATUS,RP0 ;BANCO 0
    
    MOVF    PORTA,W
    MOVWF ANTIRREBOTE
    

   MOVF    EEPROM_READ,W
   MOVWF    PORTD
   
   CALL LECTURA
   BTFSC    ANTIRREBOTE, RA1
   CALL	ESCRITURA
   
   GOTO LOOP
  
LECTURA:
    
    
    BCF	INTCON,GIE ;SE DESABILITAN LAS INTERRUPCIONES DEBIDO A QUE SI SUCEDE ALGUNA EN ESTA
    ;PARTE DEL CODIGO NO SERA POSIBLE GUARDAR EL ENTORNO DE TRABAJO (STATUS Y W) Y TODA LA EJECUCION
    ;Y MUY POSIBLEMENTE AL REGRESAR DE LA INTERRUPCION EL CODIGO NO HAGA LO QUE DEBE HACER.
    BSF	STATUS, RP1
    BSF	STATUS, RP0 ;BANCO 3
    
    BSF	EECON1, RD ;SE LEE LA EEPROM DATA
    
    BCF	STATUS,RP0 ;BANCO 2
    
    MOVF    EEDATA, W ;SE CARGA EL VALOR EN  W
    
    BCF	STATUS, RP1 ;BANCO 0
    
    MOVWF EEPROM_READ 
    
    BSF	INTCON, GIE ;SE HABILITAN LAS INTERRUPCIONES 
    
    RETURN
    
ESCRITURA:
    CALL    DELAY
    BTFSC   PORTA,RA1
    RETURN
    
    BCF	INTCON, GIE ;SE DESHABILITA POR LAS MISMAS RAZONES QUE EN LA RUTINA LECTURA
    
    MOVF    ADC,W 
    
    BSF	STATUS,RP1
    BCF	STATUS, RP0 ;BANCO 2
    
    MOVWF   EEDATA ;SE CARGA EL VALOR DEL ADC 
    
    BSF	STATUS,RP0 ;BANCO 3
    
    BSF	EECON1, WREN ;SE HABILITA LA ESCRITURA 
    
    MOVLW   H'55'
    MOVWF   EECON2
    MOVLW   H'AA'
    MOVWF   EECON2
  
    BSF	EECON1, WR ;ESCRITURA INCICIA 
    BCF	EECON1, WREN ;SE DESHABILITA LA ESCRITURA
    
    BCF	STATUS, RP1
    BCF	STATUS, RP0 ;BANCO 0 
    
    BSF	INTCON,GIE ;HABILITA INTERRUPCIONES 
    RETURN
    
  
DELAY:
    BCF	STATUS,RP1
    BCF	STATUS,RP0 ;BANCO 0
   MOVLW   .128
   MOVWF    DELAY1
   DECFSZ   DELAY1,F
   GOTO	$-1
   RETURN
   
    END