;Angel Edgardo Orellana Sutuc
; laboratorio 7 receptor
    
    
; PIC16F887 Configuration Bit Settings

; Assembly source line config statements

#include "p16f887.inc"

; CONFIG1
; __config 0xE0D4
 __CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
; CONFIG2
; __config 0xFFFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF

    
DATAS  UDATA
    VALOR RES 1
    MUX	RES 1
    W_RAM   RES 1
    STATUS_RAM RES 1
    AUXILIAR RES 1
	
RES_VECT  CODE    0x0000            ; processor reset vector
    GOTO    CONF                   ; go to beginning of program
INTER CODE 0x0004
SAVE:
    MOVWF   W_RAM
    SWAPF   STATUS,W
    MOVWF   STATUS_RAM
ISR:
    BTFSS   PIR1, 5 ;SI ESTA ACTIVA LA BANDERA
    GOTO LOAD
    
    MOVF    RCREG,W
    MOVWF   VALOR
    
LOAD:
    SWAPF   STATUS_RAM,W
    MOVWF   STATUS
    SWAPF   W_RAM,F
    SWAPF   W_RAM,W
    RETFIE
    
MAIN_PROG CODE                      ; let linker place main program

CONF
    BSF	STATUS,6
    BSF	STATUS,5 ;BANCO 3
    
    CLRF    ANSEL ;PUERTOS COMO IO DIGITALES
    
    BCF	STATUS,6 ;BANCO 1
    
    CLRF    TRISA   ;MULTIPLEXACION
    CLRF	TRISD ;TODO PUERTO D COMO SALIDA, VALOR DEL DISPLAY
    
    BSF	INTCON,7 ;SE HABILITAN LAS INTERRUPCIONES
    BSF	INTCON,6; SE HABILITAN LAS INTERRUPCIONES PERIFERICAS
    BSF	PIE1,5 ;SE HABILITA LA INTERRUPCION DE RECEPTOR EUSART
    
    BCF	TXSTA,4 ;SE HABILITA EL MODO ASINCRONO
    BSF	TXSTA,2 ;BAUD RATE HIGH SPEED
    
    MOVLW   .25
    MOVWF   SPBRG ;BAUDRATE DE 9600 (9615, EN REALIDAD)
    
    BCF	STATUS,5 ;BANCO 0
    
    BSF	RCSTA,7 ;PUERTO SERIAL HABILITADO
    BCF	RCSTA,6 ; RECEPCION DE 0 BITS
    BSF	RCSTA,4 ;RECEPCION CONTINUA
    
    CLRF    VALOR
    MOVLW B'10000000'
    MOVWF   MUX

LOOP:
    CLRF    PORTA
    COMF    MUX
    CALL    TABLA
    MOVWF   PORTD
    MOVF	MUX,W
    MOVWF   PORTA
    GOTO    LOOP
    
    
TABLA:
    MOVFW   VALOR
    BTFSC MUX,6 ; SI ESTA EN CERO SE USAN LOS BITS MENOS SIGNIFICATIVOS SI ESTA EN 1 LO CONTRARIO
    SWAPF VALOR,W
    ANDLW B'00001111' ;CONSERVAMOS SOLO EL NIBBLE INFERIOR DEL DATO GUARDADO EN W
    ADDWF   PCL,F
    ;	
    RETLW B'01110111'  ; 0  EN EL DISPLAY
    RETLW B'00010100' ;1
    RETLW B'10110011' ;2
    RETLW B'10110110';3
    RETLW B'11010100';4
    RETLW   B'11100110' ;5
    RETLW B'11100111' ;6
    RETLW   B'00110100' ;7
    RETLW   B'11110111';8
    RETLW   B'11110110';9
    RETLW   B'11110101';A
    RETLW   B'11000111';B
    RETLW   B'01100011';C
    RETLW   B'10010111';D
    RETLW   B'11100011';E
    RETLW   B'11100001';F
    
    END